const STATUS_OK = 200;
const STATUS_VALIDATION = 400;
const STATUS_NOT_FOUND = 404;
const STATUS_SERVER = 500;
const SALT_ROUND = 10;

module.exports = {
  STATUS_OK, STATUS_VALIDATION, STATUS_NOT_FOUND, STATUS_SERVER, SALT_ROUND,
};
